### ISSUE TITLE
Consider pre-commit configuration

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#3243]
If we want pre-commit control (https://pre-commit.com/), here was the `.pre-commit-config.yaml` suggested by StepSecurity:

```
repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.3
  hooks:
  - id: gitleaks
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shellcheck
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.38.0
  hooks:
  - id: eslint
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pylint-dev/pylint
  rev: v2.17.2
  hooks:
  - id: pylint
```

(We're using `tox` instead of `pylint`.)
