### ISSUE TITLE
[dependabot] Change interval from monthly to bimonthly

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#3738]
As of the newest release (https://github.com/dependabot/dependabot-core/issues/6339#issuecomment-2821835933), `.github/dependabot.yaml` now supports cronjob notation, so we can change each
```
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "UTC"
```
to
```
    schedule:
      interval: "cron"
      cronjob: "0 0 1 1-11/2 *"
```
to get dependabot updates on the first of every odd month (Jan, Mar, May, Jul, Sep, Nov).
